BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<CoverType> coverTypes = unitOfWork.CoverType.GetAll();
            return View(coverTypes);
        }

        public IActionResult Create()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(CoverType cover) {

            if (ModelState.IsValid)
            {
                if (cover.Id == 0)
                {
                    unitOfWork.CoverType.Add(cover);
                    TempData["message"] = "Save successfully";
                }
                else {
                    unitOfWork.CoverType.Update(cover);
                    TempData["message"] = "Update successfully";
                }
                unitOfWork.Save();

                return RedirectToAction("Index");
            }

            return View(cover);
        }

        public IActionResult Edit(int Id) {
            var cover = unitOfWork.CoverType.FirstOrDefault(x => x.Id == Id);
            
            if (Id == 0 || cover == null)
            {
                return NoContent();
            }

            return View("Create", cover);
        }

        public IActionResult Delete(int Id) {
            if (Id == 0) return NoContent();

            var cover = unitOfWork.CoverType.FirstOrDefault(x => x.Id == Id);
            
            if (cover == null)
                return NoContent();

            unitOfWork.CoverType.Remove(cover);
            unitOfWork.Save();

            return RedirectToAction("Index");
        }
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType


<form method="post" action="Create" asp-antiforgery="true">
    <div class="p-3">
        <div class="row">
            @if (Model == null) { 
                <h2 class="text-primary">Create Cover Type</h2>
            }else{
                <h2 class="text-primary">Edit Cover Type</h2>
            }
            
        </div>
        
        <div asp-validation-summary="All"></div>

        @if (Model != null && Model.Id != 0) {
            <input type="hidden" asp-for="Id">
        }

        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        @if (Model == null || Model.Id == 0) {
            <button type="submit" class="btn btn-primary" style="width:150px;"> Create </button>
        }
        else{
            <button type="submit" class="btn btn-primary" style="width:150px;" asp-controller="CoverType" asp-action="Create"> Update </button>
        }
        
        <a class="btn btn-secondary" style="width:150px;" asp-controller="CoverType" asp-action="Index">Back</a>
    </div>
</form>

@section scripts{
    @{
        <partial name="_validationscriptspartial" />
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row">
        <div class="col-6">
            <h2>Cover Type List</h2>
        </div>
        <div class="col-6 text-end">
            <a class="btn btn-primary" asp-controller="CoverType" asp-action="Create">
                <i class="bi bi-plus-circle"></i> &nbsp;Create New Cover Type
            </a>
        </div>
    </div>

    <br />

    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th scope="col">Cover Type Name</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>

            @foreach (CoverType coverType in Model)
            {
                <tr scope="row">
                    <td width="80%">
                        @coverType.Name
                    </td>
                    <td>
                        <a class="btn btn-warning btn-sm" asp-controller="CoverType" asp-action="Edit" asp-route-id="@coverType.Id">
                            <i class="bi bi-pencil-square"></i> &nbsp; Edit
                        </a>
                        &nbsp;
                        <a class="btn btn-danger btn-sm" asp-controller="CoverType" asp-action="Delete" asp-route-id="@coverType.Id">
                            <i class="bi bi-x-circle"></i> &nbsp; Delete
                        </a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>