BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> categories = unitOfWork.Category.GetAll();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Name.Equals(category.DisplayOrder.ToString()))
                {
                    ModelState.AddModelError("name", "Name cannot be the same with display order");
                    return View(category);
                }
                else
                {
                    if (category.Id != 0)
                    {
                        unitOfWork.Category.Update(category);
                        TempData["message"] = "Update successfully";
                    }
                    else
                    {
                        category.CreatedDateTime = DateTime.Now;
                        unitOfWork.Category.Add(category);
                        TempData["message"] = "Save successfully";
                    }

                    unitOfWork.Save();

                    return RedirectToAction("Index");
                }
            }
            else
            {
                //this will show in validation summary because keyname is not model properties
                ModelState.AddModelError("KeyName", "Please fix these following errors");
            }

            return View(category);
        }

        public IActionResult Edit(int Id)
        {
            if (Id == 0) return NoContent();

            var category = unitOfWork.Category.FirstOrDefault(x => x.Id == Id);

            if (category == null)
            {
                return NoContent();
            }

            return View("Create", category);
        }


        //Custom Action Name to invoke this action
        //[ActionName("DeletePost")]
        public IActionResult Delete(int Id)
        {

            var category = unitOfWork.Category.FirstOrDefault(x => x.Id == Id);

            if (category == null)
            {
                return NotFound();
            }

            unitOfWork.Category.Remove(category);
            unitOfWork.Save();

            TempData["message"] = "Deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllCompanies()
        {
            var company = _unitOfWork.Company.GetAll();
            return Json(new { data = company });
        }

        public IActionResult Upsert(int? Id)
        {
            Company company = new();
            
            if (Id != null && Id != 0)
            {
                company = _unitOfWork.Company.FirstOrDefault(x => x.Id == Id) ?? new();
            }

            return View(company);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Upsert(Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Id == 0)
                {
                    _unitOfWork.Company.Add(company);
                    TempData["message"] = "Save successfully";
                }
                else
                {
                    _unitOfWork.Company.Update(company);
                    TempData["message"] = "Update successfully";
                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }

            return View(company);
        }

        public IActionResult Edit(int Id)
        {
            var company = _unitOfWork.Company.FirstOrDefault(x => x.Id == Id);

            if (Id == 0 || company == null)
            {
                return NoContent();
            }

            return View("Upsert", company);
        }


        [HttpDelete]
        public IActionResult Delete(int Id)
        {
            if (Id == 0) return NoContent();

            var company = _unitOfWork.Company.FirstOrDefault(x => x.Id == Id);

            if (company == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.Company.Remove(company);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete successful" });
        }
    }
}

BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            this._unitOfWork = unitOfWork;
            this._webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllProducts() {
            var productList = _unitOfWork.Product.GetAll(includeProperties: "Category,CoverType");
            return Json(new { data = productList });
        }

        public IActionResult Upsert(int? Id)
        {
            ProductViewModel productViewModel = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                })
            };

            if (Id != null && Id != 0)
            {
                productViewModel.Product = _unitOfWork.Product.FirstOrDefault(x => x.Id == Id) ?? new();
            }

            return View(productViewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Upsert(ProductViewModel productViewModel, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null) {
                    string fileName = file.FileName;
                    string uploadDir = Path.Combine(wwwRootPath, @"images\product");
                    //string extension = Path.GetExtension(file.FileName);

                    if (productViewModel.Product.ImageUrl != null) {
                        var oldImage = Path.Combine(wwwRootPath, productViewModel.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImage)) {
                            System.IO.File.Delete(oldImage);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploadDir, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }

                    productViewModel.Product.ImageUrl = @"\images\product\" + fileName;
                }
                
                if (productViewModel.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productViewModel.Product);
                    TempData["message"] = "Save successfully";
                }
                else
                {
                    _unitOfWork.Product.Update(productViewModel.Product);
                    TempData["message"] = "Update successfully";
                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }

            return View(productViewModel);
        }

        public IActionResult Edit(int Id)
        {
            var product = _unitOfWork.Product.FirstOrDefault(x => x.Id == Id);

            if (Id == 0 || product == null)
            {
                return NoContent();
            }

            return View("Upsert", product);
        }


        [HttpDelete]
        public IActionResult Delete(int Id)
        {
            if (Id == 0) return NoContent();

            var product = _unitOfWork.Product.FirstOrDefault(x => x.Id == Id);

            if (product == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImage = Path.Combine(_webHostEnvironment.WebRootPath, product.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImage))
            {
                System.IO.File.Delete(oldImage);
            }

            _unitOfWork.Product.Remove(product);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete successful"});
        }
    }
}

BulkyBookWeb/Areas/Customer/Controllers/CartController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyBookWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewModel shoppingCart { get; set; }

        public CartController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            shoppingCart = new ShoppingCartViewModel()
            {
                ListCart = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == claim.Value, includeProperties: "Product")
            };

            foreach (var item in shoppingCart.ListCart)
            {
                var product = _unitOfWork.Product.FirstOrDefault(x => x.Id == item.ProductId);
                item.Price = getPriceBasedOnQuantity(product, item.Count);
                shoppingCart.CartTotal += (item.Price * item.Count);
            }

            return View(shoppingCart);
        }

        public IActionResult Plus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.FirstOrDefault(x => x.Id == cartId);    
            _unitOfWork.ShoppingCart.IncrementCount(cart, 1);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));  
        }

        public IActionResult Minus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.FirstOrDefault(x => x.Id == cartId);
            if (cart.Count <= 1)
            {
                _unitOfWork.ShoppingCart.Remove(cart);
            }
            else
            {
                _unitOfWork.ShoppingCart.DecrementCount(cart, 1);
            }

            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }


        private double getPriceBasedOnQuantity(Product product, int quantity) {
            if (quantity <= 50)
            {
                return product.Price;
            }
            else {
                if (quantity <= 100)
                {
                    return product.Price50;
                }
                return product.Price100;
            }
        }
    }
}

BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Bulky Book Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index" active>Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Setup</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart"></i>
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"></partial>
                    @*<form class="d-flex">
                    <input class="form-control me-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    <br /><br />
    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - BulkyBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

   
    
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>*@
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBookWeb/Views/Shared/_Notification.cshtml
@if (TempData["message"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["message"]');
    </script>
}